/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pratica04Gerenciamento;

public class Library {
    public boolean someLibraryMethod() {
    	
        return true;
    }
}
