/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pratica04Gerenciamento;

public class Library {
    public boolean someLibraryMethod() {
    	//mudança no cod 
    	System.out.println("Mudança");
    	System.out.println("Mudança2");

        return true;
    }
}
